### ISSUE TITLE
Crashes with version 4.2.0 on Windows

### ISSUE THREAD

**Issue by streamingdv** [husker-dev/openglfx#106]
[CrashLog1.log](https://github.com/user-attachments/files/20084581/CrashLog1.log)
[CrashLog2.log](https://github.com/user-attachments/files/20084610/CrashLog2.log)

**Describe the bug**
Currently I try to test the newest version with my application and I experience some crashes. With the previous version I used 4.0.5 everything worked fine. It seems that something changed or is different now in the dispose mechanism. I experience two kind of crashes

1. When I initialize GLCanvas with 1 swapBuffer like this

```
canvas = new GLCanvas(
                    LWJGLExecutor.LWJGL_MODULE,        // executor
                    false,                             // flipY
                    0,                                 // msaa
                    0.0,                               // fps
                    2,                                 // swapBuffers
                    GLInteropType.Companion.getAuto(), // interopType
                    GLProfile.CORE,                    // profile
                    false,                             // glDebug
                    null,                              // shareWith
                    -1,                                // majorVersion (Defaults.MAJOR_VERSION)
                    -1,                                // minorVersion (Defaults.MINOR_VERSION)
                    false                              // externalWindow
            );
```

This leads to a crash when I call 

`this.openGLCanvas.dispose();`

Look at the attached CrashLog1.log file. It seems to work when I set the swapBuffers parameter to 2.

2. When I use OpenGL rendering pipeline on Windows via JavaFX everything works fine but it also crashes when I call the dispose method (not immediatly but after a few seconds and setting the swapBuffers to 2 doesn't change anything). It doesn't always produce a crash log but I was able to capture one at some point, just look at CrashLog2.log. I know that using the OpenGL rendering pipeline is not recommended but it's an option in my application as it works better for some users. With the previous version I never has such an issue so maybe this can be fixed as well?

If I never call dispose it never crashes in both cases but this will lead to memory leaks of course so not really a solution. When I call dispose on my canvas I close the JavaFX stage of the canvas but not sure if that is relevant.

**Environment:**
 - OS: Windows 11
 - openglfx version: 4.2.0

**Comment by streamingdv** [comment]
Thanks, if you need more details please let me know

**Comment by husker-dev** [comment]
Dispose was completely broken in this version. Also found a memory leak on Windows with OpenGL. 
I fixed everything, but will test it on Linux and then release 4.2.1

**Comment by husker-dev** [comment]
Also added Builder to GLCanvas class for easier creation in Java
```java
GLCanvas canvas = new GLCanvas.Builder()
    .setExecutor(LWJGLExecutor.LWJGL_MODULE)
    .setContextDescription(new GLCanvas.Builder.ContextDescription.New()
        .setGLDebug(true)
        .setProfile(GLProfile.CORE))
    .build();
```

**Comment by husker-dev** [comment]
Fixed some more bugs, and released 4.2.1. Will be available in ~20 minutes

**Comment by streamingdv** [comment]
Thanks will test it out soon

**Comment by streamingdv** [comment]
@husker-dev problem 2. with the OpenGL rendering pipeline seems to be fixed, played around with it a few dozen times and no crash anymore. Tested it with swap buffers amount 1 and 2, both are working.

However 1. is still not working. When I initialize GLCanvas with just 1 swap buffer, it will crash upon disposing. The error however seems to be a different one

[hs_err_pid22988.log](https://github.com/user-attachments/files/20157178/hs_err_pid22988.log)

**Comment by husker-dev** [comment]
@streamingdv 
I am trying to reproduce the problem myself, but without success.
Can you tell me where you call `dispose()` from? 
I'm interested in the thread - is it some JavaFX thread, your own, or is it called from within the GLCanvas rendering callbacks?

**Comment by streamingdv** [comment]
Hmm interesting. I call it from the JavaFX application thread. Hoewever it seems to be some kind of race condition. If I wait a few ms before disposing the OpenGL canvas the crash does not occur anymore. It seems it clashes with the disposing of the LWJGL content

private void disposeLWJGLContent() {
        if (this.program != -1) {
            GL20.glDeleteProgram(this.program);
            this.program = -1;
        }

        if (this.shaderVert != -1) {
            GL20.glDeleteShader(this.shaderVert);
            this.shaderVert = -1;
        }
        if (this.shaderFrag != -1) {
            GL20.glDeleteShader(this.shaderFrag);
            this.shaderFrag = -1;
        }

        for (final AVOpenGLFrame frame : this.frames) {
            for (int j = 0; j < frame.tex.length; j++) {
                final int tex = frame.tex[j];
                if (tex > 0) {
                    GL11.glDeleteTextures(tex);
                }
            }
            for (int j = 0; j < frame.pbo.length; j++) {
                final int pbo = frame.pbo[j];
                if (pbo > 0) {
                    GL15.glDeleteBuffers(pbo);
                }
            }
        }

        if (this.vao != -1) {
            GL30.glDeleteVertexArrays(this.vao);
            this.vao = -1;
        }

        if (this.vbo != -1) {
            GL30.glDeleteBuffers(this.vbo);
            this.vbo = -1;
        }

        final DisposeFinishListener currentDisposeListener = this.disposeListener;
        if (currentDisposeListener != null) {
            currentDisposeListener.disposeFinish();
        }
        this.disposeListener = null;
    }

I have to refactor this logic but I think this isn't an OpenGLFX issue. Not sure why it wasn't a problem with the old version but seems to be because of some internal refactoring. So I think we can close this issue

**Comment by husker-dev** [comment]
Okay, then I'll close it. 
If it turns out that this is an openglfx problem, then reopen it.
