### ISSUE TITLE
Sometimes rendering freezes

### ISSUE THREAD

**Issue by orange451** [husker-dev/openglfx#9]
On my M1 Macbook, sometimes when the application starts, rendering will halt after a second or two. There are no errors, just the rendering callback is no longer firing.

If I resize the window, rendering is called, but only for the frames it is being resized.

This happens with default LWJGL DIRECT example

**Comment by orange451** [comment]
Should note that this is also on Java 17. Using JDK provided by default from Eclipse.

**Comment by husker-dev** [comment]
How often does this happen?
This problem is due to the node's [update flags](https://github.com/husker-dev/openglfx/blob/c938c429446fb2c0f5c87d83477c383d9f3b2ddc/lwjgl/src/main/kotlin/com/huskerdev/openglfx/lwjgl/direct/LWJGLDirect.kt#L84) that tell JavaFX that it needs to be redrawn. I thought I fixed it in one of my latest updates... Maybe I’m missing synchronization to change values

**Comment by orange451** [comment]
It is hard to gauge how often it happens. It does seem to be related to the app being booted though. I let it run for two hours yesterday and it never froze, then I restarted and it froze after 1 second. It's very intermittent.

**Comment by orange451** [comment]
I changed maven to use JavaFX version 17. This seems to **reduce** how often the application rendering freezes. However it still does **rarely** occur.

**Comment by orange451** [comment]
I have tried this on my intel-based macbook as well. Using JavaFX 17 with JDK17, I am still seeing the freeze issue (though very rare).

Repro:
https://github.com/orange451/OpenGLFX-LWJGL-Sample

**Comment by husker-dev** [comment]
I fixed this problem. But fps is now based on AnimationTimer speed.

**Comment by orange451** [comment]
Hello,
I tried out the new build. I think getFps() and getDelta() are swapped? Delta is returning whole numbers that seem to match what FPS I have set the application to run at. getFPS() is returning small numbers which look like frame-delta-times.

**Comment by husker-dev** [comment]
Yeah, I didn’t see it. Will fix it now

**Comment by husker-dev** [comment]
Fixed in the last release
